import { StoreCategory, StoreProduct } from '../types';

export const INITIAL_STORE_CATEGORIES: Array<Omit<StoreCategory, 'created_at' | 'updated_at'>> = [
  {
    id: 'cat-instagram',
    name: 'Instagram Growth',
    slug: 'instagram',
    description: 'High-retention Instagram followers, likes, reels views, story views, and engagement.',
    is_active: true,
    sort_order: 10,
  },
  {
    id: 'cat-youtube',
    name: 'YouTube Growth',
    slug: 'youtube',
    description: 'Monetizable YouTube views, subscribers, likes, shorts push, and watch hours.',
    is_active: true,
    sort_order: 20,
  },
  {
    id: 'cat-facebook',
    name: 'Facebook Services',
    slug: 'facebook',
    description: 'Facebook page followers, post reactions, video views, comments, and shares.',
    is_active: true,
    sort_order: 30,
  },
  {
    id: 'cat-twitter',
    name: 'X / Twitter Boost',
    slug: 'twitter',
    description: 'Twitter / X followers, impressions, retweets, likes, and engagement.',
    is_active: true,
    sort_order: 40,
  },
  {
    id: 'cat-telegram',
    name: 'Telegram Growth',
    slug: 'telegram',
    description: 'Telegram channel members, group members, post views, reactions, and poll votes.',
    is_active: true,
    sort_order: 50,
  },
  {
    id: 'cat-tiktok',
    name: 'TikTok Promotion',
    slug: 'tiktok',
    description: 'TikTok viral views, followers, likes, and shares for FYP push.',
    is_active: true,
    sort_order: 60,
  },
  {
    id: 'cat-threads',
    name: 'Threads Engagement',
    slug: 'threads',
    description: 'Meta Threads followers, likes, replies, and view reach.',
    is_active: true,
    sort_order: 70,
  },
  {
    id: 'cat-snapchat',
    name: 'Snapchat Services',
    slug: 'snapchat',
    description: 'Snapchat followers, spotlight views, and story views.',
    is_active: true,
    sort_order: 80,
  },
  {
    id: 'cat-pinterest',
    name: 'Pinterest Marketing',
    slug: 'pinterest',
    description: 'Pinterest profile followers, pin saves, repins, and impressions.',
    is_active: true,
    sort_order: 90,
  },
  {
    id: 'cat-linkedin',
    name: 'LinkedIn Professional',
    slug: 'linkedin',
    description: 'LinkedIn business connections, page followers, and post endorsements.',
    is_active: true,
    sort_order: 100,
  },
  {
    id: 'cat-discord',
    name: 'Discord Community',
    slug: 'discord',
    description: 'Discord verified server members and server boost perks.',
    is_active: true,
    sort_order: 110,
  },
  {
    id: 'cat-spotify',
    name: 'Spotify Music Push',
    slug: 'spotify',
    description: 'Spotify track plays, playlist followers, and monthly listeners.',
    is_active: true,
    sort_order: 120,
  },
  {
    id: 'cat-digital',
    name: 'Digital Products & Code',
    slug: 'digital-products',
    description: 'Full-stack software templates, SaaS boilerplates, and developer resources.',
    is_active: true,
    sort_order: 130,
  },
];

export const INITIAL_STORE_PRODUCTS: Array<Omit<StoreProduct, 'id' | 'created_at' | 'updated_at'>> = [
  // ==========================================
  // 1. INSTAGRAM SERVICES
  // ==========================================
  {
    name: 'Instagram Followers (HQ Real & Non-Drop)',
    slug: 'instagram-followers-hq',
    category_id: 'cat-instagram',
    category_name: 'Instagram Growth',
    platform: 'instagram',
    service_type: 'followers',
    short_description: 'High-quality non-drop Instagram followers with profile photos and bios.',
    description: 'Boost your brand credibility and social proof with permanent high-quality Instagram followers. Delivered organically at a safe pacing without requiring account passwords.',
    price_paise: 19900, // ₹199
    compare_at_price_paise: 39900,
    min_quantity: 100,
    max_quantity: 100000,
    delivery_time_info: 'Instant • 0-2 Hours',
    instructions: '1. Provide your public Instagram profile link or username.\n2. Ensure your account is set to PUBLIC during processing.\n3. Orders start automatically within 10-30 minutes.',
    access_info: 'Pacing: 1,000 - 5,000 followers / day natural ramp.',
    delivery_notes: '100% password-less & safe for personal and creator accounts.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 1,
  },
  {
    name: 'Instagram Post & Reel Likes (Instant High-Retention)',
    slug: 'instagram-likes-instant',
    category_id: 'cat-instagram',
    category_name: 'Instagram Growth',
    platform: 'instagram',
    service_type: 'likes',
    short_description: 'Instant genuine likes on your Instagram posts, photos, carousel, and reels.',
    description: 'Supercharge your post engagement algorithm with high-retention likes. Helps push your post to the Instagram Explore feed and top hashtags.',
    price_paise: 4900, // ₹49
    compare_at_price_paise: 9900,
    min_quantity: 50,
    max_quantity: 50000,
    delivery_time_info: 'Instant • 5-15 Mins',
    instructions: 'Submit the direct URL to your Instagram post or reel.',
    delivery_notes: 'Instant delivery starts within 5 minutes.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 2,
  },
  {
    name: 'Instagram Reels & Video Views (Super Fast FYP Boost)',
    slug: 'instagram-reels-views',
    category_id: 'cat-instagram',
    category_name: 'Instagram Growth',
    platform: 'instagram',
    service_type: 'views',
    short_description: 'Fast algorithmic views on Instagram Reels and video content with high watch time.',
    description: 'Give your Reels an immediate viral push on the Explore tab with rapid video views. Compatible with both fresh and existing reels.',
    price_paise: 2900, // ₹29
    compare_at_price_paise: 5900,
    min_quantity: 500,
    max_quantity: 500000,
    delivery_time_info: 'Instant • 5 Mins',
    instructions: 'Provide direct link to your Instagram Reel.',
    delivery_notes: 'Natural impression distribution.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 3,
  },
  {
    name: 'Instagram Story Views (Real Active Viewers)',
    slug: 'instagram-story-views',
    category_id: 'cat-instagram',
    category_name: 'Instagram Growth',
    platform: 'instagram',
    service_type: 'views',
    short_description: 'Views on all active Instagram stories across your profile.',
    description: 'Enhance your daily engagement metrics with real story views on all current 24-hour stories on your profile.',
    price_paise: 3900, // ₹39
    compare_at_price_paise: 7900,
    min_quantity: 100,
    max_quantity: 50000,
    delivery_time_info: 'Instant • 10 Mins',
    instructions: 'Provide your public Instagram username.',
    delivery_notes: 'Applies to all active stories.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 4,
  },
  {
    name: 'Instagram Custom Relevant Comments',
    slug: 'instagram-custom-comments',
    category_id: 'cat-instagram',
    category_name: 'Instagram Growth',
    platform: 'instagram',
    service_type: 'comments',
    short_description: 'Customized positive comments from verified & realistic looking profiles.',
    description: 'Boost conversion rates and user interactions on your sales posts, testimonials, or brand announcements with custom relevant comments.',
    price_paise: 14900, // ₹149
    compare_at_price_paise: 29900,
    min_quantity: 10,
    max_quantity: 500,
    delivery_time_info: '1-3 Hours',
    instructions: 'Submit your post link and list your desired comments (one per line).',
    delivery_notes: 'Natural spacing between comments.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 5,
  },
  {
    name: 'Instagram Post Saves & Shares (Algorithm Booster)',
    slug: 'instagram-saves-shares',
    category_id: 'cat-instagram',
    category_name: 'Instagram Growth',
    platform: 'instagram',
    service_type: 'saves',
    short_description: 'High bookmark and share counts to trigger Instagram explore recommendations.',
    description: 'Saves and shares are the #1 signal in Instagram ranking algorithm. Trigger viral reach on your educational and promotional carousels.',
    price_paise: 5900, // ₹59
    compare_at_price_paise: 11900,
    min_quantity: 100,
    max_quantity: 10000,
    delivery_time_info: 'Instant • 15 Mins',
    instructions: 'Provide post or reel link.',
    delivery_notes: 'Visible on post professional dashboard insights.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 6,
  },

  // ==========================================
  // 2. YOUTUBE SERVICES
  // ==========================================
  {
    name: 'YouTube Subscribers (Organic High-Retention)',
    slug: 'youtube-subscribers-organic',
    category_id: 'cat-youtube',
    category_name: 'YouTube Growth',
    platform: 'youtube',
    service_type: 'subscribers',
    short_description: 'Real YouTube subscribers with high retention for partner & monetization goals.',
    description: 'Grow your YouTube channel authority towards the 1,000 subscriber monetization threshold with safe non-drop subscribers.',
    price_paise: 79900, // ₹799
    compare_at_price_paise: 149900,
    min_quantity: 50,
    max_quantity: 20000,
    delivery_time_info: '24-48 Hours natural pacing',
    instructions: 'Provide full YouTube channel URL (e.g. youtube.com/@yourchannel). Ensure subscriber count is public.',
    delivery_notes: 'Natural retention pace safe for AdSense.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 10,
  },
  {
    name: 'YouTube Video Views (Monetizable & High Watch Time)',
    slug: 'youtube-views-high-retention',
    category_id: 'cat-youtube',
    category_name: 'YouTube Growth',
    platform: 'youtube',
    service_type: 'views',
    short_description: 'High watch-time video views that boost search rank and suggested videos.',
    description: 'Monetizable views with excellent audience retention to rank higher in YouTube Search, Suggested Videos, and Browse Features.',
    price_paise: 24900, // ₹249
    compare_at_price_paise: 49900,
    min_quantity: 500,
    max_quantity: 1000000,
    delivery_time_info: 'Instant • 1-4 Hours',
    instructions: 'Provide direct YouTube video link. Ensure video has no country restrictions.',
    delivery_notes: 'Real viewer referrers included.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 11,
  },
  {
    name: 'YouTube Shorts Views & Likes (Viral Feed Push)',
    slug: 'youtube-shorts-views',
    category_id: 'cat-youtube',
    category_name: 'YouTube Growth',
    platform: 'youtube',
    service_type: 'views',
    short_description: 'Rapid YouTube Shorts views and likes to trigger the Shorts Feed algorithm.',
    description: 'Push your short-form videos to thousands of viewers on the YouTube Shorts carousel.',
    price_paise: 14900, // ₹149
    compare_at_price_paise: 29900,
    min_quantity: 500,
    max_quantity: 500000,
    delivery_time_info: 'Instant • 15 Mins',
    instructions: 'Provide YouTube Shorts link.',
    delivery_notes: 'Fast feed propagation.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 12,
  },
  {
    name: 'YouTube 4,000 Watch Hours Monetization Package',
    slug: 'youtube-watch-hours-monetization',
    category_id: 'cat-youtube',
    category_name: 'YouTube Growth',
    platform: 'youtube',
    service_type: 'views',
    short_description: 'Complete 4,000 public watch hours package for YouTube Partner Program approval.',
    description: 'Fulfill YouTube 4,000 hours monetization criterion safely. Guaranteed watch hours reflected directly in YouTube Studio earn tab.',
    price_paise: 249900, // ₹2,499
    compare_at_price_paise: 499900,
    min_quantity: 1,
    max_quantity: 5,
    delivery_time_info: '3-7 Days',
    instructions: 'Channel must have at least one video of 30+ minutes or 60+ minutes duration.',
    delivery_notes: '100% monetization compliant.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 13,
  },

  // ==========================================
  // 3. FACEBOOK SERVICES
  // ==========================================
  {
    name: 'Facebook Page Followers & Likes',
    slug: 'facebook-page-followers',
    category_id: 'cat-facebook',
    category_name: 'Facebook Services',
    platform: 'facebook',
    service_type: 'followers',
    short_description: 'High-quality followers and likes for Facebook Business Pages and Creators.',
    description: 'Grow your Facebook business page followers to unlock in-stream ads eligibility and enhance brand authority.',
    price_paise: 29900, // ₹299
    compare_at_price_paise: 59900,
    min_quantity: 100,
    max_quantity: 50000,
    delivery_time_info: '1-6 Hours',
    instructions: 'Provide Facebook Page URL (e.g. facebook.com/pagename).',
    delivery_notes: 'Safe for monetized Facebook pages.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 20,
  },
  {
    name: 'Facebook Post Likes & Reactions (Love, Care, Wow)',
    slug: 'facebook-post-reactions',
    category_id: 'cat-facebook',
    category_name: 'Facebook Services',
    platform: 'facebook',
    service_type: 'likes',
    short_description: 'Custom emotional reactions (Like, Love, Care, Haha, Wow) on Facebook posts.',
    description: 'Enhance your organic feed distribution with vibrant post reactions from active profiles.',
    price_paise: 8900, // ₹89
    compare_at_price_paise: 17900,
    min_quantity: 100,
    max_quantity: 10000,
    delivery_time_info: 'Instant • 15 Mins',
    instructions: 'Provide public Facebook post URL.',
    delivery_notes: 'Mix of reactions available on request.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 21,
  },
  {
    name: 'Facebook Video & Reel Views (Instream Monetization)',
    slug: 'facebook-video-views',
    category_id: 'cat-facebook',
    category_name: 'Facebook Services',
    platform: 'facebook',
    service_type: 'views',
    short_description: '1-minute and 3-minute video views for Facebook monetization and reach.',
    description: 'Achieve the 60,000 viewed minutes milestone required for Facebook in-stream ads monetization.',
    price_paise: 4900, // ₹49
    compare_at_price_paise: 9900,
    min_quantity: 500,
    max_quantity: 100000,
    delivery_time_info: 'Instant • 30 Mins',
    instructions: 'Provide Facebook video or reel link.',
    delivery_notes: 'High retention watch sessions.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 22,
  },

  // ==========================================
  // 4. X / TWITTER SERVICES
  // ==========================================
  {
    name: 'X (Twitter) Followers (Real-Looking Profiles)',
    slug: 'twitter-followers-active',
    category_id: 'cat-twitter',
    category_name: 'X / Twitter Boost',
    platform: 'twitter',
    service_type: 'followers',
    short_description: 'High-quality Twitter/X followers to build creator and Web3 profile presence.',
    description: 'Expand your X subscriber base with realistic followers having profile avatars, headers, and past tweets.',
    price_paise: 34900, // ₹349
    compare_at_price_paise: 69900,
    min_quantity: 100,
    max_quantity: 25000,
    delivery_time_info: '2-12 Hours',
    instructions: 'Provide your X/Twitter handle (e.g. @username) or profile link.',
    delivery_notes: 'Non-drop with refill guarantee.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 30,
  },
  {
    name: 'X (Twitter) Post Likes & Retweets Combo',
    slug: 'twitter-likes-retweets',
    category_id: 'cat-twitter',
    category_name: 'X / Twitter Boost',
    platform: 'twitter',
    service_type: 'likes',
    short_description: 'Instant likes and reposts to push tweets into the "For You" timeline.',
    description: 'Get your announcements, crypto launches, or brand tweets trending with instant reposts and likes.',
    price_paise: 9900, // ₹99
    compare_at_price_paise: 19900,
    min_quantity: 50,
    max_quantity: 10000,
    delivery_time_info: 'Instant • 10 Mins',
    instructions: 'Provide direct tweet/post link.',
    delivery_notes: 'Simultaneous likes & repost distribution.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 31,
  },
  {
    name: 'X (Twitter) Impressions & Views (Analytics Push)',
    slug: 'twitter-tweet-views',
    category_id: 'cat-twitter',
    category_name: 'X / Twitter Boost',
    platform: 'twitter',
    service_type: 'views',
    short_description: 'Boost tweet view counts visible on the bottom left of every post.',
    description: 'Elevate your tweet metrics with 10,000+ views for proof of engagement and revenue share eligibility.',
    price_paise: 2900, // ₹29
    compare_at_price_paise: 5900,
    min_quantity: 1000,
    max_quantity: 1000000,
    delivery_time_info: 'Instant • 5 Mins',
    instructions: 'Provide direct tweet URL.',
    delivery_notes: 'Reflects immediately on the tweet view counter.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 32,
  },

  // ==========================================
  // 5. TELEGRAM SERVICES
  // ==========================================
  {
    name: 'Telegram Channel & Group Members (Non-Drop)',
    slug: 'telegram-members-nondrop',
    category_id: 'cat-telegram',
    category_name: 'Telegram Growth',
    platform: 'telegram',
    service_type: 'members',
    short_description: 'Stable, non-drop Telegram subscribers for channels and communities.',
    description: 'Grow your trading, crypto, business, or education Telegram channel with real active-looking subscribers.',
    price_paise: 19900, // ₹199
    compare_at_price_paise: 39900,
    min_quantity: 100,
    max_quantity: 100000,
    delivery_time_info: 'Instant • 1-3 Hours',
    instructions: 'Provide public Telegram channel/group link (e.g. t.me/channelname).',
    delivery_notes: '30-day non-drop guarantee.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 40,
  },
  {
    name: 'Telegram Post Views (Last 5-10 Posts Package)',
    slug: 'telegram-post-views',
    category_id: 'cat-telegram',
    category_name: 'Telegram Growth',
    platform: 'telegram',
    service_type: 'views',
    short_description: 'Eye icon views on your latest Telegram channel broadcasts.',
    description: 'Ensure your channel has consistent, realistic view metrics across all recently published posts.',
    price_paise: 3900, // ₹39
    compare_at_price_paise: 7900,
    min_quantity: 500,
    max_quantity: 50000,
    delivery_time_info: 'Instant • 10 Mins',
    instructions: 'Provide link to latest post in public channel.',
    delivery_notes: 'Spread across latest posts naturally.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 41,
  },
  {
    name: 'Telegram Emoji Reactions & Poll Votes',
    slug: 'telegram-reactions-poll-votes',
    category_id: 'cat-telegram',
    category_name: 'Telegram Growth',
    platform: 'telegram',
    service_type: 'likes',
    short_description: 'Custom positive emoji reactions (🔥, 👍, ❤️) and channel poll votes.',
    description: 'Make your community feel alive with active reactions and custom poll answers.',
    price_paise: 4900, // ₹49
    compare_at_price_paise: 9900,
    min_quantity: 100,
    max_quantity: 5000,
    delivery_time_info: 'Instant • 15 Mins',
    instructions: 'Provide post link and specify desired emoji or poll option number.',
    delivery_notes: 'Instant delivery.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 42,
  },

  // ==========================================
  // 6. TIKTOK SERVICES
  // ==========================================
  {
    name: 'TikTok Followers (Global HQ)',
    slug: 'tiktok-followers-global',
    category_id: 'cat-tiktok',
    category_name: 'TikTok Promotion',
    platform: 'tiktok',
    service_type: 'followers',
    short_description: 'High-quality TikTok followers to unlock LIVE streaming and creator bio links.',
    description: 'Hit the 1,000 follower requirement to unlock live-streaming and website links in your TikTok profile.',
    price_paise: 24900, // ₹249
    compare_at_price_paise: 49900,
    min_quantity: 100,
    max_quantity: 50000,
    delivery_time_info: '2-12 Hours',
    instructions: 'Provide TikTok profile link or @username.',
    delivery_notes: 'No password required.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 50,
  },
  {
    name: 'TikTok Video Views & Likes (FYP Algorithm)',
    slug: 'tiktok-views-likes',
    category_id: 'cat-tiktok',
    category_name: 'TikTok Promotion',
    platform: 'tiktok',
    service_type: 'views',
    short_description: 'Viral package for TikTok videos to trend on the "For You" page.',
    description: 'Massive view counts and matching likes to push your video into regional and global viral algorithms.',
    price_paise: 7900, // ₹79
    compare_at_price_paise: 15900,
    min_quantity: 500,
    max_quantity: 1000000,
    delivery_time_info: 'Instant • 10 Mins',
    instructions: 'Provide TikTok video link.',
    delivery_notes: 'High speed processing.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 51,
  },

  // ==========================================
  // 7. THREADS SERVICES
  // ==========================================
  {
    name: 'Threads Followers & Likes Boost',
    slug: 'threads-followers-likes',
    category_id: 'cat-threads',
    category_name: 'Threads Engagement',
    platform: 'threads',
    service_type: 'followers',
    short_description: 'Meta Threads followers and post likes from real active profiles.',
    description: 'Establish early authority on Meta new Threads social platform with steady followers and post engagement.',
    price_paise: 24900, // ₹249
    compare_at_price_paise: 49900,
    min_quantity: 100,
    max_quantity: 20000,
    delivery_time_info: '1-4 Hours',
    instructions: 'Provide your Threads profile URL or post link.',
    delivery_notes: 'Synced directly with Instagram ecosystem.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 60,
  },

  // ==========================================
  // 8. SNAPCHAT SERVICES
  // ==========================================
  {
    name: 'Snapchat Public Profile Followers & Views',
    slug: 'snapchat-followers-views',
    category_id: 'cat-snapchat',
    category_name: 'Snapchat Services',
    platform: 'snapchat',
    service_type: 'followers',
    short_description: 'Public profile subscribers and spotlight video views.',
    description: 'Grow your Snapchat creator presence and qualify for the Snapchat Spotlight revenue share program.',
    price_paise: 39900, // ₹399
    compare_at_price_paise: 79900,
    min_quantity: 100,
    max_quantity: 10000,
    delivery_time_info: '6-24 Hours',
    instructions: 'Provide public Snapchat username or spotlight link.',
    delivery_notes: 'Compatible with public creator profiles.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 70,
  },

  // ==========================================
  // 9. PINTEREST SERVICES
  // ==========================================
  {
    name: 'Pinterest Followers & Pin Saves (E-commerce Booster)',
    slug: 'pinterest-followers-saves',
    category_id: 'cat-pinterest',
    category_name: 'Pinterest Marketing',
    platform: 'pinterest',
    service_type: 'followers',
    short_description: 'Pinterest board followers and pin repins for blog & e-commerce traffic.',
    description: 'Drive high-converting buyer traffic from Pinterest to your Shopify, Etsy, or business store with saves and repins.',
    price_paise: 24900, // ₹249
    compare_at_price_paise: 49900,
    min_quantity: 100,
    max_quantity: 20000,
    delivery_time_info: '2-8 Hours',
    instructions: 'Provide Pinterest profile or pin link.',
    delivery_notes: 'Long-term SEO indexing value.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 80,
  },

  // ==========================================
  // 10. LINKEDIN SERVICES
  // ==========================================
  {
    name: 'LinkedIn Company & Personal Profile Followers',
    slug: 'linkedin-followers-hq',
    category_id: 'cat-linkedin',
    category_name: 'LinkedIn Professional',
    platform: 'linkedin',
    service_type: 'followers',
    short_description: 'High-caliber corporate and professional followers for LinkedIn pages.',
    description: 'Build B2B trust and enterprise credibility with industry-focused LinkedIn followers for your personal brand or startup page.',
    price_paise: 69900, // ₹699
    compare_at_price_paise: 129900,
    min_quantity: 100,
    max_quantity: 10000,
    delivery_time_info: '12-36 Hours safe pacing',
    instructions: 'Provide LinkedIn personal profile URL or company page link.',
    delivery_notes: '100% compliant with LinkedIn safety limits.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 90,
  },
  {
    name: 'LinkedIn Post Reactions & Endorsements',
    slug: 'linkedin-post-reactions',
    category_id: 'cat-linkedin',
    category_name: 'LinkedIn Professional',
    platform: 'linkedin',
    service_type: 'likes',
    short_description: 'Celebrate, Insightful, and Love reactions on LinkedIn articles and posts.',
    description: 'Maximize algorithmic reach on your LinkedIn business insights, hiring posts, and thought-leadership articles.',
    price_paise: 24900, // ₹249
    compare_at_price_paise: 49900,
    min_quantity: 50,
    max_quantity: 2000,
    delivery_time_info: '1-4 Hours',
    instructions: 'Provide direct link to the LinkedIn post.',
    delivery_notes: 'Real looking corporate profiles.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 91,
  },

  // ==========================================
  // 11. DISCORD SERVICES
  // ==========================================
  {
    name: 'Discord Verified Server Members (Online / Offline)',
    slug: 'discord-server-members',
    category_id: 'cat-discord',
    category_name: 'Discord Community',
    platform: 'discord',
    service_type: 'members',
    short_description: 'Realistic Discord server members with avatars to populate new servers.',
    description: 'Create an active, bustling server atmosphere for your Web3, gaming, SaaS, or creator Discord community.',
    price_paise: 34900, // ₹349
    compare_at_price_paise: 69900,
    min_quantity: 100,
    max_quantity: 50000,
    delivery_time_info: 'Instant • 1-2 Hours',
    instructions: 'Provide permanent Discord invite link (set to never expire).',
    delivery_notes: 'Non-kick guarantee.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 100,
  },
  {
    name: 'Discord Server Boosts (Level 1, 2, 3 Perks)',
    slug: 'discord-server-boosts',
    category_id: 'cat-discord',
    category_name: 'Discord Community',
    platform: 'discord',
    service_type: 'members',
    short_description: 'Unlock 100+ emoji slots, 1080p stream quality, custom invite banners, and vanities.',
    description: 'Get your Discord server instantly upgraded with 1-month or 3-month server boosts.',
    price_paise: 59900, // ₹599
    compare_at_price_paise: 119900,
    min_quantity: 2,
    max_quantity: 14,
    delivery_time_info: 'Instant • 30 Mins',
    instructions: 'Provide permanent server invite link.',
    delivery_notes: 'Full boost badge active for 30 days.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 101,
  },

  // ==========================================
  // 12. SPOTIFY SERVICES
  // ==========================================
  {
    name: 'Spotify Artist & Playlist Followers',
    slug: 'spotify-artist-followers',
    category_id: 'cat-spotify',
    category_name: 'Spotify Music Push',
    platform: 'spotify',
    service_type: 'followers',
    short_description: 'Followers for Spotify Artist profiles and curated playlists.',
    description: 'Boost your artist ranking on Spotify algorithm to get listed on Release Radar and Discover Weekly.',
    price_paise: 24900, // ₹249
    compare_at_price_paise: 49900,
    min_quantity: 100,
    max_quantity: 50000,
    delivery_time_info: '1-6 Hours',
    instructions: 'Provide Spotify artist profile or playlist link.',
    delivery_notes: 'Eligible for Spotify for Artists analytics.',
    status: 'PUBLISHED',
    featured: false,
    sort_order: 110,
  },
  {
    name: 'Spotify Track Plays & Streams (High Retention)',
    slug: 'spotify-track-streams',
    category_id: 'cat-spotify',
    category_name: 'Spotify Music Push',
    platform: 'spotify',
    service_type: 'views',
    short_description: 'Royalty-eligible, high-retention Spotify streams from premium global listeners.',
    description: 'Drive stream counts on your newly released singles and albums with safe 90s+ playback retention.',
    price_paise: 19900, // ₹199
    compare_at_price_paise: 39900,
    min_quantity: 1000,
    max_quantity: 500000,
    delivery_time_info: 'Instant • 2-12 Hours',
    instructions: 'Provide Spotify track URL (e.g. open.spotify.com/track/...).',
    delivery_notes: 'Safe for distributor royalties.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 111,
  },

  // ==========================================
  // 13. PRE-EXISTING DIGITAL CODE/BOILERPLATE
  // ==========================================
  {
    name: 'Next.js SaaS Starter & Boilerplate Kit',
    slug: 'nextjs-saas-starter',
    category_id: 'cat-digital',
    category_name: 'Digital Products & Code',
    platform: 'digital',
    service_type: 'boilerplate',
    short_description: 'Production-ready Next.js 15, Supabase Auth, Stripe/FamGateway, and Tailwind CSS kit.',
    description: 'Launch your SaaS in days rather than months. Includes authentication, multi-tenant RBAC, billing, email templates, and automated database migrations.',
    price_paise: 99900, // ₹999
    compare_at_price_paise: 249900,
    file_name: 'vyapaarpro-saas-starter.zip',
    access_link: 'https://github.com/vyapaarpro-templates/nextjs-saas-starter',
    instructions: '1. Unzip the package.\n2. Run `npm install`.\n3. Configure `.env` with Supabase keys.\n4. Run `npm run dev`.',
    access_info: 'GitHub Template Access: Request repo invite with your purchase order number.',
    license_key: 'VP-SAAS-PRO-8821',
    delivery_notes: 'Lifetime access & free updates included.',
    status: 'PUBLISHED',
    featured: true,
    sort_order: 120,
  },
];
